=== SierraSoftworks/schemas/src/git-tool/v2/template.schema.json
{
    "$schema": "http://json-schema.org/schema",
    "description": "A template which will be consumed by Git-Tool to update a user's config file with a new application or service.",
    "type": "object",
    "required": [
        "name",
        "description",
        "version",
        "configs"
    ],
    "properties": {
        "name": {
            "type": "string",
            "description": "The human readable name of the application or service provided by this template."
        },
        "description": {
            "type": "string",
            "description": "The human readable description of the application or service provided by this template, including some information about what the application or service does and where more information can be found about it."
        },
        "version": {
            "type": "string",
            "description": "The version of the template, following [SemVer](https://semver.org) conventions.",
            "pattern": "^\\d+\\.\\d+\\.\\d+(-.+)?$"
        },
        "configs": {
            "type": "array",
            "description": "The list of config changes which should be applied when this template is installed.",
            "items": {
                "type": "object",
                "description": "A config change which should be applied when this template is installed.",
                "required": [
                    "platform"
                ],
                "oneOf": [
                    {
                        "required": ["app"],
                        "properties": {
                            "service": false
                        }
                    },
                    {
                        "required": ["service"],
                        "properties": {
                            "app": false
                        }
                    }
                ],
                "additionalProperties": false,
                "properties": {
                    "platform": {
                        "type": "string",
                        "description": "The platform that this config entry should be applied on.",
                        "default": "any",
                        "enum": [
                            "any",
                            "windows",
                            "linux",
                            "darwin"
                        ]
                    },
                    "app": {
                        "$ref": "https://schemas.sierrasoftworks.com/git-tool/v2/config.schema.json#/definitions/Application"
                    },
                    "service": {
                        "$ref": "https://schemas.sierrasoftworks.com/git-tool/v2/config.schema.json#/definitions/Service"
                    }
                }
            }
        }
    }
}

=== SierraSoftworks/schemas/git-tool/v1/template.example.json
{
  "$schema": "./template.schema.json",
  "name": "Demo",
  "description": "This is an example of how to create a config template",
  "version": "1.0.0",
  "configs": [
    {
      "platform": "any",
      "service": {
        "domain": "github.com",
        "website": "https://{{ .Service.Domain }}/{{ .Repo.FullName }}",
        "httpUrl": "https://{{ .Service.Domain }}/{{ .Repo.FullName }}.git",
        "gitUrl": "git@{{ .Service.Domain }}:{{ .Repo.FullName }}.git",
        "pattern": "*/*"
      }
    },
    {
      "platform": "windows",
      "app": {
        "name": "shell",
        "command": "powershell.exe"
      }
    },
    {
      "platform": "linux",
      "app": {
        "name": "shell",
        "command": "pwsh"
      }
    }
  ]
}

=== SierraSoftworks/schemas/src/git-tool/v2/template.example.json
{
  "$schema": "./template.schema.json",
  "name": "Demo",
  "description": "This is an example of how to create a config template",
  "version": "1.0.0",
  "configs": [
    {
      "platform": "any",
      "service": {
        "name": "gh",
        "website": "https://github.com/{{ .Repo.FullName }}",
        "gitUrl": "git@github.com:{{ .Repo.FullName }}.git",
        "pattern": "*/*",
        "api": {
          "kind": "GitHub/v3",
          "url": "https://api.github.com"
        }
      }
    },
    {
      "platform": "windows",
      "app": {
        "name": "shell",
        "command": "powershell.exe"
      }
    },
    {
      "platform": "linux",
      "app": {
        "name": "shell",
        "command": "pwsh"
      }
    }
  ]
}
